# Generated by Django 5.2.4 on 2025-08-29 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myfolio_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='Customers',
        ),
    ]
